services:
  scraper:
    build:
      context: ./scraper
    environment:
      BUCKET: ${BUCKET}
      SECRET: ${SECRET}
    volumes:
      - "~/.aws:/root/.aws"
    restart: no
  front-builder:
    build:
      context: ./front
    environment:
      BUCKET: ${BUCKET}
      DESTINATION: ${DESTINATION}
    volumes:
      - "~/.aws:/root/.aws"
    restart: no
