name: Run tests

on: [push]

permissions:
  contents: read

jobs:
  test-backend:
    runs-on: ubuntu-latest
    name: Run `unittest`
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: |
        cd ./scraper && poetry install

    - name: Run tests
      run: |
        cd ./scraper && poetry run python -m unittest discover . -v
